language: ruby
cache: bundler
rvm:
  - 2.3.0
script:
  - bundle install --without production
  - bundle exec rails db:migrate 
  - bundle exec rails test
after_success:
  - ./ci/success
after_failure:
  - ./ci/failure
