# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a15744377e4f4d38c89f2590c103e2b90a272aad0ea69b1e19e0abe091fe202271d6b70f3e8452edb6dbbb35235f53c959257edfaabcf01cdebf4f245b192b5

test:
  secret_key_base: 340c433ddb057e7832bc8c21b82b5f50834dad0a3fc8f25c4f82fc9a39a825b0e46d25d64e48bb1824f279de3f6e39cbf7739d614257469ae6b7f74d4aa6d175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
