#!/bin/bash

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d "access_token=${ACCESS_TOKEN}&arg=red" "https://api.particle.io/v1/devices/${DEVICE_ID}/led"
