#!/bin/bash

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: f7386639-84cd-90c7-ddca-6d34f636892c" -d 'access_token=e3d0963c580a1b9bf4717e7fe4bf1072b18b694b&arg=green' "https://api.particle.io/v1/devices/35002e000647353138383138/led"
