#!/bin/bash

curl -X --verbose POST -H "Content-Type: application/x-www-form-urlencoded" -h "cache-control: no-cache" -h "postman-token: f7386639-84cd-90c7-ddca-6d34f636892c" -d "access_token=${ACCESS_TOKEN}&arg=green" "https://api.particle.io/v1/devices/${DEVICE_ID}/led"
